export enum OPCODE {
  AND = 'and',
  OR = 'or',
  XOR = 'xor',
  ADD = 'add',
  SUB = 'sub',
  SLL = 'sll',
  SRA = 'sra',
  SRL = 'srl',
  NOT = 'not',
  COM = 'com',
  MVHL = 'mvhl',
  MVLH = 'mvlh',
  MVH = 'mvh',
  LH = 'lh',
  LI = 'li',
  SH = 'sh',
  SLT = 'slt',
  SOE = 'soe',
  BOZ = 'boz',
  BONZ = 'bonz',
  JAL = 'jal',
  JALR = 'jalr',
  HALT = 'halt',
}
